io:
  - open
  - openat
  - close
  - read
  - write
proc:
  - fork
  - clone
  - kill
  - wait4
  - waitid
fs:
  - chdir
  - creat
  - fchdir
  - flock
  - fstat
  - fsync
  - ftruncate
  - getcwd
  - link
  - lstat
  - mkdir
  - rmdir
  - stat
  - symlink
  - truncate
  - unlink
  - open
  - openat
  - close
  - read
  - write
memory:
  - brk
  - mmap
  - munmap
  - mprotect
  - madvise
  - mincore
  - mremap
  - msync
net:
  # - sendfile
  - socket
  - connect
  - accept
  - sendto
  - recvfrom
  - sendmsg
  - recvmsg
  - shutdown
  - bind
  - listen
  - getsockname
  - getpeername
  - socketpair
  - getsockopt
  - setsockopt
ipc:
  - msgget
  - msgsend
  - msgrcv
  - msgctl
  - semget
  - semop
  - semctl
  - shmget
  - shmat
  - shmdt
  - shmctl
